name: PR Terraform Plan

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build-and-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: docker
        run: |
          IMAGE_TAG=front-pr-${{ github.event.pull_request.number }}
          cd backend_image && docker build -t $IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Debug image tag output
        run: |
          echo "Docker image tag is: ${{ steps.docker.outputs.image_tag }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::877680973630:role/Terraform_ECS_Backent
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform refresh
        run: terraform refresh

      - name: Terraform Plan (pass docker image)
        run: terraform plan  -no-color -var="docker_image=${{ steps.docker.outputs.image_tag }}" > front-plan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: front-plan.txt

      - name: Send plan to Telegram (as file)
        run: |
          curl -s -F document=@front-plan.txt \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument

