name: PR Terraform Plan

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build-and-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: docker
        run: |
          IMAGE_TAG=front-pr-${{ github.event.pull_request.number }}
          cd backend_image && docker build -t $IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Debug image tag output
        run: |
          echo "Docker image tag is: ${{ steps.docker.outputs.image_tag }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::877680973630:role/Terraform_ECS_Backent
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform refresh
        id: refresh
        run: terraform refresh
        continue-on-error: true

      - name: Terraform Plan 
        id: plan
        run:  terraform plan  -no-color -var="docker_image=${{ steps.docker.outputs.image_tag }}" > front-plan.txt
        continue-on-error: true

      - name: Upload Terraform Plan
        if: steps.refresh.outcome == 'success' && steps.plan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: front-plan.txt


      - name: Comment Plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: front-plan.txt
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: Send plan to Telegram (as file)
        if: steps.refresh.outcome == 'success' && steps.plan.outcome == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: front-plan.txt
          message: "✅ Terraform plan was successful for frontend."


      - name: Send Telegram message
        if: steps.refresh.outcome != 'success' || steps.plan.outcome != 'success'
        uses: appleboy/telegram-action@master
        with: 
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "❌ Terraform plan failed for frontend. Please check the GitHub Actions logs."
